sudo: false
language: python
python:
  - "2.7"
before_install:
  - sh -c set
  - git config --global user.email "travis-tahoe@tahoe-lafs.org"
  - git config --global user.name "Travis Tahoe"
  - git fetch --depth=1000
  - python misc/build_helpers/show-tool-versions.py
install:
  - pip install tox coverage coveralls
before_script: python setup.py build
script: tox
